### PR TITLE
use https for links to pear.php.net

### PR DESCRIPTION
**Pull request by staabm**
in the process of converting most http to https I found this links... 

I double checked the new links work, but cannot test whether this might cause a problem in the app itself, as I cannot test it locally.

### CODE REVIEW

**Comment by staabm** [comment]
Friendly ping

**Comment by staabm** [comment]
@cmb69 could you take a look at this patch?

**Comment by cmb69** [comment]
> as I cannot test it locally.

Same here, sorry.

**Comment by petk** [comment]
Applied via 13b4777b61788de255af07798043bee2c7ce30e1 Thanks.

Yes, PEAR configuration seems to be otherwise disabled at the time of this writing.

**Comment by php-pulls** [comment]
**Comment on behalf of petk at php.net:**

Applied via 13b4777b61788de255af07798043bee2c7ce30e1

**Pull request closed without merging**
