### PR TITLE
add local admin for the Chinese translation

### PR DESCRIPTION
**Pull request by jhdxr**
Hi, I'm proposing to make Dai Jie (daijie@php.net) and me (jhdxr@php.net) to be the local admin for Chinese translation.

### CODE REVIEW

**Comment by jhdxr** [comment]
hi @cmb69 @petk could you take a look at this? thanks.

**Comment by petk** [comment]
Sure. Thanks for volunteering. I'm currently only working on code patches here and there. Maybe @salathe or @cmb69 can help here out with this?

**Comment by php-pulls** [comment]
**Comment on behalf of cmb at php.net:**

This makes perfect sense. Applied as 59be6f2.

**Comment by jhdxr** [comment]
lots of thanks @petk @cmb69

**Pull request closed without merging**
